<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Aw2Rmdtoc</AssemblyName>
    <RootNamespace>alan_wake_2_rmdtoc_Tool</RootNamespace>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="lz4net" Version="1.0.15.93" />
  </ItemGroup>
</Project>

